Efmub-Ogy/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Contact__c.object
<CustomObject>
    <description>Represents an additional Contact related to a Case.</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which the Contact is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Case_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>REL-{00000000}</displayFormat>
        <label>Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/CaseContactHandlerTest.cls
/*******************************************************//**

@class      CaseContactHandlerTest

@brief      Test Class for the CaseContactHandler Class

@author     Glyn Anderson (LiquidHub.GHA)

@version    2015-12-01  LiquidHub.GHA
    Created.

@see        CaseContactHandler
@see        CaseContact (trigger)

    (c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

    This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

@isTest
public class CaseContactHandlerTest
{
    public static testMethod void testCaseContactHandler()
    {
        CWTest testResults = new CWTest( 'testCaseContactHandler' );

        Account account = new Account
        (   Name        = 'Test Account'
        );
        insert account;

        Contact contact = new Contact
        (   LastName    = 'Test',
            AccountId   = account.Id
        );
        insert contact;

        Case    theCase = new Case
        (   ContactId   = contact.Id
        );
        insert theCase;

       // Case_Contact__c caseContact = new Case_Contact__c
     //   (   Case__c     = theCase.Id,
       //     Contact__c  = contact.Id
       // );

        testResults.startTest();

        //insert caseContact;

        //  test code goes here...

        testResults.stopTest();
        testResults.report();
    }
}