Efmub-Ogy/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Complaint__c.object
<CustomObject>
    <description>Associates a complaint code to both a Case and a Flight Leg</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Case Complaint is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaint Codes</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Flight Leg to which this Case Complaint is related.</inlineHelpText>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Complaint</label>
    <nameField>
        <displayFormat>CPT-{00000000}</displayFormat>
        <label>Case Complaint</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Flight_Leg__c.object
<CustomObject>
    <description>Represents a specific flight leg.</description>
    <fields>
        <fullName>Case_Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Complaint</label>
        <referenceTo>Case_Complaint__c</referenceTo>
        <relationshipLabel>Flight Legs</relationshipLabel>
        <relationshipName>Flight_Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flight Leg</label>
    <nameField>
        <label>Flight Leg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/CaseComplaintHandlerTest.cls
/*******************************************************//**

@class		CaseComplaintHandlerTest

@brief		Test Class for the CaseComplaintHandler Class

@author		Glyn Anderson (LiquidHub.GHA)

@version	2015-12-01	LiquidHub.GHA
	Created.

@see		CaseComplaintHandler
@see		CaseComplaint (trigger)

	(c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

@isTest
public class CaseComplaintHandlerTest
{
	public static testMethod void testCaseComplaintHandler()
	{
		CWTest testResults = new CWTest( 'testCaseComplaintHandler' );

		Account	account	= new Account
		(	Name		= 'Test Account'
		);
		insert account;

		Contact	contact	= new Contact
		(	LastName	= 'Test',
			AccountId	= account.Id
		);
		insert contact;

		Case	theCase	= new Case
		(	ContactId	= contact.Id
		);
		insert theCase;

		Flight_Leg__c	flightLeg	= new Flight_Leg__c();
		insert flightLeg;

		Case_Complaint__c	complaint	= new Case_Complaint__c
		(	Case__c			= theCase.Id,
			Flight_Leg__c	= flightLeg.Id
		);

		testResults.startTest();

		insert complaint;

		//	test code goes here...

		testResults.stopTest();
		testResults.report();
	}
}