Efmub-Ogy/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Compensation__c.object
<CustomObject>
    <description>Represents compensation to a passenger.</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Compensation is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <inlineHelpText>The Contact to whom this Compensation is related.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Flight Leg to which this Compensation is related.</inlineHelpText>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>COMP{00000000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Flight_Leg__c.object
<CustomObject>
    <description>Represents a specific flight leg.</description>
    <label>Flight Leg</label>
    <nameField>
        <label>Flight Leg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/CompensationHandlerTest.cls
/*******************************************************//**

@class		CompensationHandlerTest

@brief		Test Class for the CompensationHandler Class

@author		Glyn Anderson (LiquidHub.GHA)

@version	2015-12-01	LiquidHub.GHA
	Created.

@see		CompensationHandler
@see		Compensation (trigger)

	(c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

@isTest
public class CompensationHandlerTest
{
	public static testMethod void testCompensationHandler()
	{
		CWTest testResults = new CWTest( 'testCompensationHandler' );

		Account	account	= new Account
		(	Name		= 'Test Account'
		);
		insert account;

		Contact	contact	= new Contact
		(	LastName	= 'Test',
			AccountId	= account.Id
		);
		insert contact;

		Case	theCase	= new Case
		(	ContactId	= contact.Id
		);
		insert theCase;

		Flight_Leg__c	flightLeg	= new Flight_Leg__c();
		insert flightLeg;

		Compensation__c	complaint	= new Compensation__c
		(	Case__c			= theCase.Id,
			Contact__c		= contact.Id,
			Flight_Leg__c	= flightLeg.Id
		);

		testResults.startTest();

		insert complaint;

		//	test code goes here...

		testResults.stopTest();
		testResults.report();
	}
}