Efmub-Ogy/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Investigation__c.object
<CustomObject>
    <description>Represents a request for information from other Delta departments or external entities.</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Investigation is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <label>Investigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/InvestigationHandlerTest.cls
/*******************************************************//**

@class		InvestigationHandlerTest

@brief		Test Class for the InvestigationHandler Class

@author		Glyn Anderson (LiquidHub.GHA)

@version	2015-12-01	LiquidHub.GHA
	Created.

@see		InvestigationHandler
@see		Investigation (trigger)

	(c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

@isTest
public class InvestigationHandlerTest
{
	public static testMethod void testInvestigationHandler()
	{
		CWTest testResults = new CWTest( 'testInvestigationHandler' );

		Account	account	= new Account
		(	Name		= 'Test Account'
		);
		insert account;

		Contact	contact	= new Contact
		(	LastName	= 'Test',
			AccountId	= account.Id
		);
		insert contact;

		Case	theCase	= new Case
		(	ContactId	= contact.Id
		);
		insert theCase;

		Investigation__c	investigation	= new Investigation__c
		(	Case__c		= theCase.Id
		);

		testResults.startTest();

		insert investigation;

		//	test code goes here...

		testResults.stopTest();
		testResults.report();
	}
}