Efmub-Ogy/src/objects/Airline_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Airline Codes</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_Code__c</fullName>
        <externalId>true</externalId>
        <label>IATA Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ICAO_Code__c</fullName>
        <label>ICAO Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Airline Code</label>
</CustomObject>

Efmub-Ogy/src/objects/Airport_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_Code__c</fullName>
        <label>IATA Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ICAO_Code__c</fullName>
        <label>ICAO Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Airport Code</label>
</CustomObject>

Efmub-Ogy/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Complaint_Location__c</fullName>
        <description>Delta CC - US-29 - Req-2002</description>
        <label>Complaint Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACS Gate</fullName>
                </value>
                <value>
                    <fullName>ACS Ticket Counter</fullName>
                </value>
                <value>
                    <fullName>Inflight</fullName>
                </value>
                <value>
                    <fullName>Flight Ops</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Complaint__c.object
<CustomObject>
    <description>Associates a complaint code to both a Case and a Flight Leg</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Case Complaint is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaint Codes</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Complaint_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Complaint Codes can be selected.</errorMessage>
            <filterItems>
                <field>Complaint_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active Complaint Codes can be selected.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Complaint_Code__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complaint_Location__c</fullName>
        <label>Complaint Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACS Gate</fullName>
                </value>
                <value>
                    <fullName>ACS Ticket Counter</fullName>
                </value>
                <value>
                    <fullName>Inflight</fullName>
                </value>
                <value>
                    <fullName>Flight Ops</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Flight Leg to which this Case Complaint is related.</inlineHelpText>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Complaint</label>
    <nameField>
        <displayFormat>CPT-{00000000}</displayFormat>
        <label>Case Complaint</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Flight_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Flight Details</relationshipLabel>
        <relationshipName>Case_Flight_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Case Flight Details</relationshipLabel>
        <relationshipName>Case_Flight_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Flight Detail</label>
    <nameField>
        <displayFormat>CSF-{0000000}</displayFormat>
        <label>Case Flight Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Flight Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Complaint_Code__c.object
<CustomObject>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>If( ISPICKVAL(Type__c, &apos;Delta&apos;), Level_1__c+ &apos; | &apos;+ Level_2__c+ &apos; | &apos;+ Level_3__c+ &apos; | &apos;+ Level_4__c+ &apos; | &apos;+ Keywords__c, IF(ISPICKVAL(Type__c, &apos;DOT&apos;), Name+ &apos; | &apos;+ Level_1__c+ &apos; | &apos;+ Level_2__c+ &apos; | &apos;+ Level_3__c+ &apos; | &apos;+ Level_4__c+ &apos; | &apos;+ Keywords__c,TEXT(Type__c)+ &apos; | &apos;+ Name+ &apos; | &apos;+ Level_1__c+ &apos; | &apos;+ Level_2__c+ &apos; | &apos;+ Level_3__c+ &apos; | &apos;+ Level_4__c+ &apos; | &apos;+ Keywords__c) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <label>Complaint Code</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Flight_Leg__c.object
<CustomObject>
    <description>Represents a specific flight leg.</description>
    <fields>
        <fullName>ActualArrivalTime__c</fullName>
        <label>Actual Arrival Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActualDepartureTime__c</fullName>
        <label>Actual Departure Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alerts__c</fullName>
        <formula>Handling_Notes_Alert__c &amp;  Flight_Grid_Alert__c</formula>
        <label>Alerts</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ArrivalAirport__c</fullName>
        <label>Arrival Airport</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Complaint</label>
        <referenceTo>Case_Complaint__c</referenceTo>
        <relationshipLabel>Flight Legs</relationshipLabel>
        <relationshipName>Flight_Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_Manually__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created Manually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DepartureAirport__c</fullName>
        <label>Departure Airport</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightNumber__c</fullName>
        <label>Flight Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InTime__c</fullName>
        <inlineHelpText>Actual Time during arrival when the Flight is at the Gate</inlineHelpText>
        <label>In Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegMileage__c</fullName>
        <label>Leg Mileage</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MarketingAirlineCode__c</fullName>
        <label>Marketing Carrier</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OffTime__c</fullName>
        <inlineHelpText>Actual Time during departure Time when the wheels of the Flight take off from the Ground</inlineHelpText>
        <label>Off Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OnTime__c</fullName>
        <inlineHelpText>Actual Time during the arrival when the wheels of the Flight are on the Ground</inlineHelpText>
        <label>On Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OperatingAirlineCode__c</fullName>
        <label>Operating Carrier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OperatingFlightNumber__c</fullName>
        <label>Operating Flight Number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OutTime__c</fullName>
        <label>Out Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledArrivalTime__c</fullName>
        <label>Scheduled Arrival Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledDepartureTime__c</fullName>
        <label>Scheduled Departure Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight Leg</label>
    <nameField>
        <label>Flight Leg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/PNR__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PNRs</relationshipLabel>
        <relationshipName>PNRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>PNRs</relationshipLabel>
        <relationshipName>PNRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Locator__c</fullName>
        <label>Record Locator</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>PNR</label>
    <nameField>
        <displayFormat>PNR-{00000000}</displayFormat>
        <label>PNR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PNRs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/SkyFinderFlightLegController.cls
public class SkyFinderFlightLegController {
    
    public Id                                   caseId                 { get; set; }
    public Boolean                              initialized            { get; set; }
    public Boolean                              hasCaseId              { get; set; }   
    public Case                                 flightLegCase          { get; set; }
    public Set<String>                          attachedFlightLegNames;
    public String          selectedFlightLegName  { get; set; } 
    public List<FlightLegUtils.Flightleg> pnrFlightLegList
    { 
        get{ return pnrFltsMap == null || pnrFltsMap.isEmpty() ? new List<FlightLegUtils.Flightleg>() : pnrFltsMap.values(); } 
        set; 
    }
    public Boolean         hasPNRFlightLegs       { get{ return pnrFlightLegList == null || pnrFlightLegList.isEmpty() ? false : true; } set; }
    public List<SelectOption> airlineCodes
    {
        get
        {
            if (airlineCodes != null) return airlineCodes;
            airlineCodes = new List<SelectOption>();

            for(Airline_Code__c airlineCode : [
                SELECT   Id, IATA_Code__c, ICAO_Code__c, Name, Country__c
                FROM     Airline_Code__c
                WHERE    IATA_Code__c != Null AND IATA_Code__c != ''
                ORDER BY Sort_Order__c NULLS LAST, IATA_Code__c
            ]) {
                airlineCodes.add(new SelectOption(airlineCode.IATA_Code__c, airlineCode.IATA_Code__c + ' - ' + /* airlineCode.ICAO_Code__c + ' - ' + */ airlineCode.Name + ' - ' + airlineCode.Country__c));
            }

            return airlineCodes;
        }
        private set;
    }

    public List<SelectOption> airportCodes
    {
        get
        {
            if (airportCodes != null) return airportCodes;
            airportCodes = new List<SelectOption>();
            for(Airport_Code__c airportCode : [
                SELECT   Id, IATA_Code__c, ICAO_Code__c, Full_Name__c, City__c, State__c, Country__c
                FROM     Airport_Code__c
                WHERE    IATA_Code__c != Null AND IATA_Code__c != ''
                ORDER BY IATA_Code__c
            ]) {
                airportCodes.add(new SelectOption(airportCode.IATA_Code__c, airportCode.IATA_Code__c + ' - ' + /* airportCode.ICAO_Code__c + ' - ' + */ airportCode.Full_Name__c + ' - ' + airportCode.City__c + (airportCode.State__c == Null ? '' : ', ' + airportCode.State__c) + ' ' + airportCode.Country__c));
            }
            return airportCodes;
        }
        private set;
    }

     public List<FlightLegUtils.Flightleg> potentialFlightLegs
    { 
        get{ return potFltsMap == null || potFltsMap.isEmpty() ? new List<FlightLegUtils.Flightleg>() : potFltsMap.values(); } 
        set; 
    }
    public Boolean  hasPotentialFlightLegs { get{ return potentialFlightLegs == null || potentialFlightLegs.isEmpty() ? false : true; } set; }
    public FlightLegUtils.searchParameters      params                
    { 
        get
        { 
            if (params == null) params = new FlightLegUtils.searchParameters();
            return params;
        }
        set; 
    }
     public List<FlightLegUtils.Complaint> attachedComplaints     
    { 
        get{ return atthdCmpltsMap == null || atthdCmpltsMap.isEmpty() ? new List<FlightLegUtils.Complaint>() : atthdCmpltsMap.values(); } 
        set; 
    }
    
    public list<Flight_Leg__c> attachedFlights{get;set;}
     public Map<String,FlightLegUtils.Flightleg> potFltsMap          // key is FlightLegName     
    { 
        get
        {
            if(potFltsMap == null ) potFltsMap = new Map<String,FlightLegUtils.Flightleg>();
            return potFltsMap;
        } 
        set;
    } 
     public Map<String,FlightLegUtils.Complaint> atthdCmpltsMap      // key is FlightLegName
    { 
        get
        {
            if(atthdCmpltsMap == null) atthdCmpltsMap = new Map<String,FlightLegUtils.Complaint>();
            return atthdCmpltsMap;
        } 
        set;
    }
    public Map<String,FlightLegUtils.Flightleg> pnrFltsMap         // key is FlightLegName      
    { 
        get
        {
            if(pnrFltsMap == null ) pnrFltsMap = new Map<String,FlightLegUtils.Flightleg>();
            return pnrFltsMap;
        } 
        set; 
    }   
    public List<String>    collumnNames           { get; set; }
    public SkyFinderFlightLegController() 
    {
        caseId = ApexPages.currentPage().getParameters().get('id');
        idCheck = 'check';
        initialized = false;
        hasCaseId = false;
        
                // TODO: now query all of the fields
        if(caseId != null)
        {
            List<case> theCases =
            ([
                SELECT id, Subject, CaseNumber, Reason, PNR__c,
                    ContactId, AccountId
                FROM case
                WHERE id = :caseId
            ]);
            if (!theCases.isEmpty()) 
            {
                flightLegCase = theCases[0];
                hasCaseId = true;
            }
        }

        params.Task = new Task();
        params.PNR = flightLegCase == null ? null : flightLegCase.PNR__c;

        if(!String.isBlank(caseId)) 
        {
            /*if(!String.isBlank(params.PNR)) 
            {
                clickSearch();
            }
            */
            if (potFltsMap != null) pnrFltsMap = potFltsMap.clone();        // with ondemand parameter, should never be null
            else pnrFltsMap = new Map<String, FlightLegUtils.Flightleg>();

            potFltsMap = new Map<String, FlightLegUtils.Flightleg>();
            params.PNR = null;
        }
        collumnNames = new List<String>{ '', 'Flight', 'Schd Dep', 'Dep City', 'Schd Arr', 'Arr City', '# Of Cases', 'Alerts'};
        resetFlightLegs();
    }
    
     public void resetFlightLegs() {
        Set<Id> flightLegIds = new Set<Id>();
        attachedFlights = new list<Flight_Leg__c>();
        Map<Id,Set<Id>> CaseCountMap = new Map<Id,Set<Id>>(); //Map<FlightLedId,Set<CaseId>>
        Map<Id,Decimal> CompensationTotal = new Map<Id,Decimal>();
        Map<String,Id> complaintsNameToId = new Map<String,Id>();  //Map<FightLegName,Flight_Leg__c>

        attachedFlightLegNames = new Set<String>();
        String caseIDCompare = caseId == null ? '' : 'Case__c = \'' + caseId + '\' AND ';
        String whereClause = caseIDCompare + 'Case__c != Null';
        /*for(Case_Complaint__c complaint : FlightLegUtils.queryCaseComplaints(whereClause)) 
        {
            if (complaint.Flight_Leg__c == null) continue; // caseComplaints might not have a flightLeg
            if (atthdCmpltsMap == null) atthdCmpltsMap = new Map<String,FlightLegUtils.Complaint>();            
            atthdCmpltsMap.put(complaint.Flight_Leg__r.Name,FlightLegUtils.convertCaseComplaintFromDatabaseToInternal(complaint));
            flightLegIds.add(complaint.Flight_Leg__c);
            attachedFlightLegNames.add(complaint.Flight_Leg__r.Name);
            complaintsNameToId.put(complaint.Flight_Leg__r.Name,complaint.Flight_Leg__c);
        }*/
        set<id> flghtId = new set<id>();
        for(Case_Flight_Detail__c cfg : [select id,Flight__c from Case_Flight_Detail__c where Case__c = :caseId])
        {
            flghtId.add(cfg.Flight__c);
        }
        if(flghtId.size() > 0)
        {
            attachedFlights = [select id,name,FlightNumber__c,ScheduledDepartureTime__c,ScheduledArrivalTime__c,DepartureAirport__c,ArrivalAirport__c from Flight_Leg__c where id IN :flghtId];
        }

        Set<ID> CasesSuperSet = new Set<ID>(); 
        whereClause = 'Case__c != null';
        if (!flightLegIds.isEmpty()) whereClause += ' AND Flight_Leg__c != null AND Flight_Leg__c IN ' + FlightLegUtils.setIDtoString(flightLegIds); //Flight_Leg__c IN :flightLegIds AND Case__c != Null

        for(Case_Complaint__c complaint : FlightLegUtils.queryCaseComplaints(whereClause))
        {
            CasesSuperSet.add(complaint.Case__c);
            Set<Id> theCases = CaseCountMap.get(complaint.Flight_Leg__c);
            if (theCases == null) theCases = new Set<Id>();
            theCases.add(complaint.Case__c);
            CaseCountMap.put(complaint.Flight_Leg__c,theCases);
        }

        for(FlightLegUtils.Complaint aComp : attachedComplaints)
        {
            Id flID = complaintsNameToId.get(aComp.flightName);
            Set<Id> theCases = CaseCountMap.get(flID);
            aComp.caseCount = theCases == null ? 0 : theCases.size();
            aComp.compAvg = 0;
        }
    }
    public void clickSearch()
    {
        initialized = true;
        system.debug('clickSearch-in --> '+params.Carrier+' '+params.FlightNumber+' '+params.Task.ActivityDate);
        boolean flag1 = cityCheck(params.Destination);
        boolean flag2 = cityCheck(params.Origin);
        system.debug('validation done');
        if(String.isBlank(params.PNR) && (String.isBlank(params.Carrier) || String.isBlank(params.FlightNumber) || params.Task.ActivityDate == Null)) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Search must include either a PNR or a carrier, flight number, and date.'));
            return;
        }
        if(flag1 && !string.isBlank(params.Destination))
        {
            system.debug('inside if');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter valid origin/destination'));
            return;
        }
        if(flag2 && !string.isBlank(params.Origin))
        {
            system.debug('inside else');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter valid origin/destination'));
            return;
        }

        Set<Id> flightLegIds = new Set<Id>();
        /*if (attachedFlightLegNames == null) attachedFlightLegNames = new Set<String>();
        String caseIDCompare = caseId == null ? '' : 'Case__c = \'' + caseId + '\' AND ';
        String whereClause = caseIDCompare + 'Case__c != Null';
        whereClause += ' AND Flight_Leg__c != Null'; // skip caseComplaints without a flightLeg

        for( Case_Complaint__c caseComplaint : FlightLegUtils.queryCaseComplaints( whereClause ) )
        {
            flightLegIds.add(caseComplaint.Flight_Leg__c);
            attachedFlightLegNames.add(caseComplaint.Flight_Leg__r.Name);
        }
        */
        Map <String,FlightLegUtils.Flightleg> searchResults = new Map<String,FlightLegUtils.Flightleg>();   // Key is Flightleg Name
        system.debug('pnr value --> '+params.PNR);
        if(String.isNotBlank(params.PNR)) {
            
            searchResults.putAll(FlightLegUtils.doCalloutsPnr(params.PNR));
        } else if(String.isNotBlank(params.Carrier) && String.isNotBlank(params.FlightNumber) && params.Task.ActivityDate != Null) {
            system.debug('else-executed');
            searchResults.putAll(FlightLegUtils.doCalloutsDetails(params));
            system.debug('else-Completed');
        }

        resetFlightLegs();  // TODO : do I need to do this here?
        // loop by index because these are ordered ??  TODO:  order means nothing here -- set index in doCallout calls
        for(Integer i = 0; i < searchResults.values().size(); i++) {
            system.debug('crew check --> '+searchResults.values()[i].crew);
            searchResults.values()[i].index = i;
            searchResults.values()[i].attached = attachedFlightLegNames.contains(searchResults.values()[i].name);
            if (searchResults.values()[i].name != null) potFltsMap.put(searchResults.values()[i].name, searchResults.values()[i]);
            // if the order is important, the map loses it, because the page display will
            // iterate over the values in arbitrary order
        }

        //  This counts the number of unique cases associated with each flight leg
        Map<Id, Integer> flightlegCaseCountsMap = new Map<Id, Integer>(); // <flightleg id, case count>

        if (potFltsMap != null && !potFltsMap.isEmpty())
        {
            CWQuery caseCountsQuery  = CWQuery.newAggregateQuery('Case_Complaint__c').countDistinct('Case__c','numCases').groupBy('Flight_Leg__c');
            caseCountsQuery.newWhereClause().isIn('Flight_Leg__r.Name',new List<String>(potFltsMap.keySet()));
            for ( AggregateResult result : caseCountsQuery.aggregateQuery() )
            {
                flightlegCaseCountsMap.put((Id) result.get('Flight_Leg__c'), (Integer) result.get('numCases'));
                //Id      thisFlightLegId     = (Id) result.get('Flight_Leg__c');
                //Integer hasThisManyCases    = (Integer) result.get('numCases');
            }

            CWQuery queryFlightLeg = CWQuery.newQuery('Flight_Leg__c').addAllFields();
            queryFlightLeg.newORWhereClause().isIN('Name', new List<String>( potFltsMap.keyset() ));
            for (Flight_Leg__c foundFlightLeg : (List<Flight_Leg__c>)queryFlightLeg.query())
            {
                FlightLegUtils.FlightLeg internal = potFltsMap.get(foundFlightLeg.Name);
                if (internal == null) continue; // shouldn't happen
                internal.id = foundFlightLeg.id;
                internal.flightleg = foundFlightLeg;
                internal.caseCount = flightlegCaseCountsMap.get(foundFlightLeg.id) != null ?
                                        flightlegCaseCountsMap.get(foundFlightLeg.id) : 0;
                FlightLegUtils.Complaint theComplaint = atthdCmpltsMap.get(foundFlightLeg.Name);
                if (theComplaint != null) theComplaint.caseCount = internal.caseCount;
            }
        }
        else // nothing found
        {
            // the initialized flag prevents the error message on page load
            // the clickSearch function is called to find the flights attached to the PNR on page load
            if (initialized) ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'No Matches Found for Search'));
        }
        initialized = true;
        return;
    }
    
    public boolean cityCheck(string cityName)
    {
        boolean flag = true;
        system.debug('city name --> '+cityName);
        list<string> str = cityName.split(' - ');
        list<Airport_Code__c > airport = [select id,IATA_Code__c, name from Airport_Code__c  where IATA_Code__c = :str[0]];
        if(airport.size() > 0)flag = false;
        return flag;
    }
    public string idCheck{get;set;}
    public string casecomplaint{get;set;}
    public void AcceptContactforCreate()    // function to be used on 'SkyFinder Console landed' version of this page
    {
        
        casecomplaint = '';
        system.debug('flight name --> '+selectedFlightLegName+'  '+params.Task.ActivityDate+'  '+params.Destination+'  '+params.Origin);
        if (String.isBlank(selectedFlightLegName)) return;   
        
       FlightLegUtils.flightLeg pnrSelectedFlightLeg = pnrFltsMap.get(selectedFlightLegName);
       FlightLegUtils.flightLeg potSelectedFlightLeg = potFltsMap.get(selectedFlightLegName);
       
       list<Flight_Leg__c> flighLegs = new list<Flight_Leg__c>();
       flighLegs = [select id,name,ActualDepartureTime__c from Flight_Leg__c where Name = :selectedFlightLegName and ActualDepartureTime__c = :potSelectedFlightLeg.ActualDepartureTime and ActualArrivalTime__c = :potSelectedFlightLeg.ActualArrivalTime];
       id toBeAttached;
       
       if(flighLegs.size() == 0){
           system.debug('flighLegs :-' + flighLegs.size());
        toBeAttached = FlightLegUtils.saveFlightLeg(potSelectedFlightLeg == null ? pnrSelectedFlightLeg : potSelectedFlightLeg);
       }
       else{
           system.debug('flighLegs else part:-');
           toBeAttached = flighLegs[0].id;
       }
       // Id toBeAttached = FlightLegUtils.saveFlightLeg(potSelectedFlightLeg == null ? pnrSelectedFlightLeg : potSelectedFlightLeg);
       /* if (toBeAttached == null)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Unable to Create Flightleg'));
            return;
        }
        */
        system.debug('id value --> '+toBeAttached);
        idCheck = toBeAttached;
        system.debug('id value --> '+idCheck );
        
        if(caseId == Null) return;  // this is true if we got to this page via skyfinder and there is no case -- we are done
        Case_Flight_Detail__c csf = new Case_Flight_Detail__c(Case__c = caseId,Flight__c=toBeAttached);
        insert csf;
        if((params.PNR != null)&&(params.PNR != ''))
        {
            PNR__c pnr = new PNR__c(Case__c = caseId,Record_Locator__c = params.PNR, Flight_Leg__c = toBeAttached);
            insert pnr;
        }
        Flight_Leg__c fg = [select id,name,FlightNumber__c,ScheduledDepartureTime__c,ScheduledArrivalTime__c,DepartureAirport__c,ArrivalAirport__c from Flight_Leg__c where id = :toBeAttached];
        attachedFlights.add(fg);
        casecomplaint = ApexPages.currentPage().getParameters().get('caseComplaint');
        system.debug('casecomplaint --> '+casecomplaint);
        if(!string.isblank(casecomplaint))
        {
            Case_Complaint__c cc = new Case_Complaint__c(id=casecomplaint,Flight_Leg__c = toBeAttached);
            update cc;
        }
        // Handle attaching to the case
        // check to see whether this is already attached, and if not ... attach it
        /*List<Case_Complaint__c> Junctions = 
        [
            SELECT Id, Case__c, Flight_Leg__c,Flight_Leg__r.Alerts__c
            FROM   Case_Complaint__c
            WHERE  Case__c = :caseId AND Flight_Leg__c = :toBeAttached
        ];*/
      /*  List<Case_Complaint__c> Junctions = 
        [
            SELECT Id, Case__c, Flight_Leg__c
            FROM   Case_Complaint__c
            WHERE  Case__c = :caseId AND Flight_Leg__c = :toBeAttached
        ];
        Case_Complaint__c newComplaintObj;
        if (Junctions.isEmpty()) newComplaintObj = new Case_Complaint__c(Case__c = caseId, Flight_Leg__c = toBeAttached);
        else newComplaintObj = Junctions[0];
        upsert newComplaintObj;
        //Query the complaint to get the needed fields -- TODO : move this into the convert function?
        String whereClause = 'Id = \'' + newComplaintObj.id + '\'';
        List<Case_Complaint__c> queriedComplaint = FlightLegUtils.queryCaseComplaints(whereClause); // WHERE   Id = :newComplaintObj.id
System.Debug('C whereClause ' + whereClause);
/*
        [
            SELECT   Id, Flight_Leg__c,
                     Complaint_Code__r.Display_Name__c,
                     Complaint_Location__c,
                     Flight_Leg__r.Name,
                     Flight_Leg__r.MarketingAirlineCode__c,
                     Flight_Leg__r.OperatingAirlineCode__c,
                     Flight_Leg__r.FlightNumber__c,
                     Flight_Leg__r.DepartureAirport__c,
                     Flight_Leg__r.ArrivalAirport__c,
                     Flight_Leg__r.ScheduledDepartureTime__c,
                     Flight_Leg__r.ScheduledArrivalTime__c,
                     Flight_Leg__r.ActualDepartureTime__c,
                     Flight_Leg__r.ActualArrivalTime__c,
                     Flight_Leg__r.InTime__c,
                     Flight_Leg__r.OutTime__c,
                     Flight_Leg__r.OffTime__c,
                     Flight_Leg__r.OnTime__c,
                     Flight_Leg__r.LegMileage__c,
                     Flight_Leg__r.Alerts__c
            FROM     Case_Complaint__c
            WHERE   Id = :newComplaintObj.id 
        ];
*//*
        if (queriedComplaint.isEmpty()) return;
        FlightLegUtils.Complaint complaintInternal = FlightLegUtils.convertCaseComplaintFromDatabaseToInternal(queriedComplaint[0]);
        Boolean complaintUpdated = false;
        if (complaintInternal != null) atthdCmpltsMap.put(selectedFlightLegName, complaintInternal);
        if (potSelectedFlightLeg != null) 
        {
            potSelectedFlightLeg.attached = true;
            potSelectedFlightLeg.caseCount = potSelectedFlightLeg.caseCount == null ? 1 : potSelectedFlightLeg.caseCount++;
            complaintInternal.caseCount = potSelectedFlightLeg.caseCount;
            complaintUpdated = true;
        }
        if (pnrSelectedFlightLeg != null)
        {
            pnrSelectedFlightLeg.attached = true;
            pnrSelectedFlightLeg.caseCount = pnrSelectedFlightLeg.caseCount == null ? 1 : pnrSelectedFlightLeg.caseCount++;
            if (!complaintUpdated) complaintInternal.caseCount = pnrSelectedFlightLeg.caseCount;
        } 
        */
    }
    
    public void clickCreateManuallyFlightLeg()
    {
               
        if(String.isBlank(params.Carrier) || String.isBlank(params.Origin) || String.isBlank(params.Destination) || (params.Task.ActivityDate == null)) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, 'Creating a Flight Leg manually requires a Marketing carrier,origin, destination, date.'));
            return;
        }
        
         /*Start Added by Anil to check origin and destination in valid*/
        
        boolean flag1 = cityCheck(params.Destination);
        boolean flag2 = cityCheck(params.Origin);
        system.debug('validation done');
        
        if(flag1 && !string.isBlank(params.Destination))
        {
            system.debug('inside if');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter valid origin/destination'));
            return;
        }
        if(flag2 && !string.isBlank(params.Origin))
        {
            system.debug('inside else');
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please enter valid origin/destination'));
            return;
        }
        
        /*End*/
        

        Date d = params.Task.ActivityDate;
        String departureDate = '';
        if(d != null){
         departureDate = DateTime.newInstance(d.year(), d.month(), d.day(), 0, 0, 0).format('yyyy-MM-dd');
        }
        String name = FlightLegUtils.makeUniqueName(params.Carrier.left(2), params.FlightNumber, departureDate, params.Origin.left(3), params.Destination.left(3));
        
        Flight_Leg__c flightLeg = new Flight_Leg__c();
        flightLeg.Name                      = name;
        flightLeg.MarketingAirlineCode__c   = params.Carrier.left(2);
        flightLeg.OperatingAirlineCode__c   = params.Carrier.left(2);  
        flightLeg.FlightNumber__c           = FlightLegUtils.makeFourDigits(params.FlightNumber);       
        flightLeg.OperatingFlightNumber__c  = FlightLegUtils.makeFourDigits(params.FlightNumber);
        flightLeg.DepartureAirport__c       = params.Origin.left(3);
        flightLeg.ArrivalAirport__c         = params.Destination.left(3);
        flightLeg.ScheduledDepartureTime__c = departureDate;
        flightLeg.Created_Manually__c       = true;
        insert flightLeg;

        Case_Complaint__c caseComplaint = new Case_Complaint__c();
        caseComplaint.Case__c = caseId;
        caseComplaint.Flight_Leg__c = flightLeg.Id;
        insert caseComplaint;
        
        FlightLegUtils.FlightLeg flg = new FlightLegUtils.FlightLeg();
        flg.name = name;
        flg.DepartureAirport = params.Origin.left(3);
        flg.ArrivalAirport = params.Destination.left(3);
        flg.ScheduledDepartureTime = departureDate;
        flg.MarketingAirlineCode = params.Carrier.left(2);
        flg.OperatingAirlineCode = params.Carrier.left(2); 
        flg.FlightNumber = FlightLegUtils.makeFourDigits(params.FlightNumber);
        flg.OperatingFlightNumber = FlightLegUtils.makeFourDigits(params.FlightNumber);
        potFltsMap.put(flightLeg.Name,flg);
        system.debug('value check --> '+potFltsMap);
        resetFlightLegs();
    }
    public void clearSearch()
    {
        potFltsMap = new Map<String, FlightLegUtils.FlightLeg>();
        params = new FlightLegUtils.searchParameters();   
        params.Task = new Task();
        params.PNR = flightLegCase == null ? null : flightLegCase.PNR__c;       
//      params.Task.ActivityDate = null;
//      Render_OperCarrier = false;
    }
     public void clickRemoveFlightLeg() {
        if(String.isBlank(selectedFlightLegName)) return;
        list<Case_Flight_Detail__c> csf = [select id from Case_Flight_Detail__c where Flight__c = :selectedFlightLegName and Case__c = :caseId];
        delete csf;
        integer i = 0;
        for(Flight_Leg__c fl:attachedFlights)
        {
            if(fl.id == selectedFlightLegName)
                break;
        }
        attachedFlights.remove(i);
        /*FlightLegUtils.Complaint theComplaint = atthdCmpltsMap.remove(selectedFlightLegName);
        FlightLegUtils.FlightLeg potFlight = potFltsMap.get(selectedFlightLegName);
        FlightLegUtils.FlightLeg pnrFlight = pnrFltsMap.get(selectedFlightLegName);
        ID potFlightID = potFlight == null ? null : potFlight.id;
        ID pnrFlightID = pnrFlight == null ? null : pnrFlight.id;
        SkyFinderUtils.idTupple myID = SkyFinderUtils.validateID( theComplaint.Id );

        if(theComplaint != null && theComplaint.Id != null && myID.isValid && myID.myType == Case_Complaint__c.sObjectType) 
        { 
            delete new Case_Complaint__c (Id = theComplaint.Id);
        }

        // clean up any other complaints that attach this flightLeg to this case
        Map<Id, Case_Complaint__c> complaintDanglers = new Map<Id, Case_Complaint__c>
        (
            [
                SELECT id 
                FROM Case_Complaint__c 
                WHERE (Flight_Leg__c = :pnrFlightID OR Flight_Leg__c = :potFlightID) AND Flight_Leg__c != null AND Case__c = :caseId
            ]
        );
        delete complaintDanglers.values();
        
        // mark it as not attached
        if (potFlight != null) 
        {
            potFlight.attached = false;
            potFlight.caseCount--;
        }
        if (pnrFlight != null) 
        {
            pnrFlight.attached = false;
            pnrFlight.caseCount--;
        }*/
    }

}