Efmub-Ogy/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Disability_Code_Required__c</fullName>
        <label>Disability Code Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOT disability code is required</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>DOT disability code is not required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Received_Date__c</fullName>
        <label>Initial Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Received_Via__c</fullName>
        <label>Received From</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACS</fullName>
                </value>
                <value>
                    <fullName>Air France</fullName>
                </value>
                <value>
                    <fullName>ANAC</fullName>
                </value>
                <value>
                    <fullName>Attorney General</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Corporate Communications</fullName>
                </value>
                <value>
                    <fullName>CTA</fullName>
                </value>
                <value>
                    <fullName>Customer Care</fullName>
                </value>
                <value>
                    <fullName>Delta Private Jets</fullName>
                </value>
                <value>
                    <fullName>Delta Vacations</fullName>
                </value>
                <value>
                    <fullName>Disability Voicemail</fullName>
                </value>
                <value>
                    <fullName>DOT</fullName>
                </value>
                <value>
                    <fullName>Executive</fullName>
                </value>
                <value>
                    <fullName>Flight Ops</fullName>
                </value>
                <value>
                    <fullName>Government Affairs</fullName>
                </value>
                <value>
                    <fullName>INDECOPI</fullName>
                </value>
                <value>
                    <fullName>In-Flight Services</fullName>
                </value>
                <value>
                    <fullName>KLM</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>OCSD</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Passenger Refunds</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
                <value>
                    <fullName>RIO SAC</fullName>
                </value>
                <value>
                    <fullName>Risk Management</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>SERNAC</fullName>
                </value>
                <value>
                    <fullName>SkyMiles</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Disability</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>Record Type to support general Disability inquiries submitted from the DOT</description>
        <label>Disability</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Complaint__c.object
<CustomObject>
    <description>Associates a complaint code to both a Case and a Flight Leg</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Case Complaint is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaint Codes</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Complaint_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Complaint Codes can be selected.</errorMessage>
            <filterItems>
                <field>Complaint_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active Complaint Codes can be selected.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Complaint_Code__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disability_Code__c</fullName>
        <label>Disability Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Vision Impaired</fullName>
                </value>
                <value>
                    <fullName>Hearing Impaired</fullName>
                </value>
                <value>
                    <fullName>Vision &amp; Hearing Impaired</fullName>
                </value>
                <value>
                    <fullName>Paraplegic</fullName>
                </value>
                <value>
                    <fullName>Quadriplegic</fullName>
                </value>
                <value>
                    <fullName>Other Wheelchair</fullName>
                </value>
                <value>
                    <fullName>Oxygen</fullName>
                </value>
                <value>
                    <fullName>Stretcher</fullName>
                </value>
                <value>
                    <fullName>Other Disability</fullName>
                </value>
                <value>
                    <fullName>Other Assistive Device</fullName>
                </value>
                <value>
                    <fullName>Mentally Impaired</fullName>
                </value>
                <value>
                    <fullName>Communicable Disease</fullName>
                </value>
                <value>
                    <fullName>Allergies</fullName>
                </value>
                <value>
                    <fullName>Case is greater than 45 days</fullName>
                </value>
                <value>
                    <fullName>Telephone case</fullName>
                </value>
                <value>
                    <fullName>No flight info</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Disability_Group__c</fullName>
        <label>Disability Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Refusal to Board Passenger</fullName>
                </value>
                <value>
                    <fullName>Refusal to Board w/o Attendant</fullName>
                </value>
                <value>
                    <fullName>Security Issues Regarding Disability</fullName>
                </value>
                <value>
                    <fullName>Aircraft Not Accessible</fullName>
                </value>
                <value>
                    <fullName>Airport Not Accessible</fullName>
                </value>
                <value>
                    <fullName>Advance Notice Dispute</fullName>
                </value>
                <value>
                    <fullName>Seating Accommodation</fullName>
                </value>
                <value>
                    <fullName>Failure to Provide Assistance</fullName>
                </value>
                <value>
                    <fullName>Damage to Assistive Device</fullName>
                </value>
                <value>
                    <fullName>Storage and Delay of Assistive Device</fullName>
                </value>
                <value>
                    <fullName>Service Animal Problem</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory Info.</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>No DOT Code</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Flight Leg to which this Case Complaint is related.</inlineHelpText>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Complaint</label>
    <nameField>
        <displayFormat>CPT-{00000000}</displayFormat>
        <label>Case Complaint</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Complaint_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disability_Code_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disability Code Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint Code</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Flight_Leg__c.object
<CustomObject>
    <description>Represents a specific flight leg.</description>
    <fields>
        <fullName>Case_Complaint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Complaint</label>
        <referenceTo>Case_Complaint__c</referenceTo>
        <relationshipLabel>Flight Legs</relationshipLabel>
        <relationshipName>Flight_Legs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flight Leg</label>
    <nameField>
        <label>Flight Leg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/SkyFinderCaseComplaintControllerTest.cls
@isTest
public class SkyFinderCaseComplaintControllerTest {

    @isTest(seeAllData=true)
    static void basicGetters()
    {
        SkyFinderCaseComplaintController controller = new SkyFinderCaseComplaintController();
        controller.newComplaintDescription = Null;
        controller.newComplaintLocation    = Null;
        controller.newFlightLegId          = Null;
        controller.newFlightLegAirport     = Null;
        controller.complaintCodeId         = Null;
        controller.hasCaseId               = False;
        controller.caseNumber              = Null;
        controller.topCaseId               = Null;
        controller.hasPnr                  = False;
        controller.pnr                     = Null;
        controller.hasContactName          = False;
        controller.contactName             = Null;
        controller.contactId               = Null;
        controller.hasComplaintCity        = False;
        controller.complaintCity           = Null;
        controller.hasSkyMilesNumber       = False;
        controller.skyMilesNumber          = Null;
        controller.caseComplaint           = Null;
        controller.attachedComplaints      = Null;

        controller.getDataJson();
        controller.getComplaintLocations();
        controller.getComplaintCodesList2();
        controller.getAirportLocations();
    }

    @isTest(seeAllData=true)
    static void testContructor()
    {
        //Complaint_Code__c cc=new Complaint_Code__c();
        
        
        Complaint_Code__c testComplaintCode = [
            SELECT Id, Name
            FROM   Complaint_Code__c
            WHERE  Disability_Code_Required__c = FALSE AND Active__c = TRUE
            LIMIT  1
        ];

        Case testCase = new Case(
            RecordTypeId='0120S0000004LRzQAM',
            Subject = 'Test Case 123',
            Origin='Phone',
            Type='Disability',
            Status ='Open',
            Received_Via__c='BBB',
            CurrencyIsoCode ='USD',
            Received_Date__c= Date.parse('4/11/2017')
        );
        upsert testCase;      

        //Flight_Leg__c testFlightLeg0 = new Flight_Leg__c(Name = 'DL0123 2016-06-21 ATL ABQ');
        //Flight_Leg__c testFlightLeg1 = new Flight_Leg__c(Name = 'DL1234 2016-06-21 MSP ATL');
        //insert new List<Flight_Leg__c>{ testFlightLeg0, testFlightLeg1 };

        Case_Complaint__c testCaseComplaint0 = new Case_Complaint__c(
            Case__c       = testCase.Id
            //,Flight_Leg__c = testFlightLeg0.Id
        );
        Case_Complaint__c testCaseComplaint1 = new Case_Complaint__c(
            Case__c           = testCase.Id,
            //Flight_Leg__c     = testFlightLeg0.Id,
            Complaint_Code__c = testComplaintCode.Id
        );
        Case_Complaint__c testCaseComplaint2 = new Case_Complaint__c(
            Case__c           = testCase.Id,
            //Flight_Leg__c     = testFlightLeg0.Id,
            Complaint_Code__c = testComplaintCode.Id
        );
        insert new List<Case_Complaint__c>{ testCaseComplaint0, testCaseComplaint1, testCaseComplaint2 };

        PageReference tpageRef = Page.SkyFinderCaseComplaintPage;
        Test.setCurrentPage(tpageRef);
        ApexPages.currentPage().getParameters().put('id', testCase.Id);

        ApexPages.StandardController sc = new ApexPages.StandardController(testCase);
        SkyFinderCaseComplaintController controller = new SkyFinderCaseComplaintController();

        controller.getFlightLegs();

        controller.clickRemoveComplaint();
        controller.complaintCodeId = testCaseComplaint1.Id;
        controller.clickRemoveComplaint();
        controller.complaintCodeId = testCaseComplaint2.Id;
        controller.clickRemoveComplaint();

        controller.clickResetComplaint();

        controller.complaintCodeId = testCaseComplaint0.Id;
        controller.clickAddComplaint(); // error
        controller.newComplaintDescription = '';
        controller.clickAddComplaint(); // error
        controller.newComplaintDescription = 'abc';
        controller.clickAddComplaint(); // error
        controller.newComplaintDescription = '|abc';
        controller.clickAddComplaint(); // error
        controller.newComplaintDescription = '|' + testComplaintCode.Name;
        controller.clickAddComplaint(); // error
        controller.caseComplaint.Disability_Group__c = 'Other';
        controller.clickAddComplaint(); // error
        controller.caseComplaint.Disability_Code__c = 'Oxygen';
        controller.clickAddComplaint(); // success fill in existing flight leg
        controller.clickAddComplaint(); // success copy flight leg
    }
}