Efmub-Ogy/src/objects/CaseAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Case1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link From Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Associations</relationshipLabel>
        <relationshipName>CaseAssociations_case</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Link To Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Linked From</relationshipLabel>
        <relationshipName>related_cases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Association</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/Case_Association_Handler_Test.cls
// Author: Vincent Lui

@isTest
public class Case_Association_Handler_Test {
    static testMethod void Case_Association_Handler_Test()
    {
        CWTest testResults = new CWTest( 'testCheckRecursive' );
        CaseAssociation__c ca1 = new CaseAssociation__c();
        ca1.Case__c = '5000S000001EIcH';
        ca1.Case1__c = '5000S000001EK3J';

        testResults.startTest();        
        insert ca1;
        
        checkRecursive.SetRunFlag(true);
        
        // CaseAssociation__c ca2 = new CaseAssociation__c();
        // ca2.Case__c = '5000S000001EIcH';
        // ca2.Case1__c = '5000S000001EK3J';
        // insert ca2;
        
        checkRecursive.SetRunFlag(true);
        
        CaseAssociation__c ca3 = new CaseAssociation__c();
        ca3 = [SELECT Id FROM CaseAssociation__c WHERE Case__c = '5000S000001EIcH' AND Case1__c = '5000S000001EK3J'];
        delete ca3;
        
        testResults.stopTest();
        testResults.report();
  }
}