Efmub-Ogy/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Disability_Code_Required__c</fullName>
        <label>Disability Code Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DOT disability code is required</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>DOT disability code is not required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSR__c</fullName>
        <description>Delta CC - US-29 - Req-166</description>
        <label>SSR</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>DOT</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>Record Type to support general DOT inquiries</description>
        <label>DOT</label>
    </recordTypes>
    <recordTypes>
        <fullName>Disability</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>Record Type to support general Disability inquiries submitted from the DOT</description>
        <label>Disability</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Case_Complaint__c.object
<CustomObject>
    <description>Associates a complaint code to both a Case and a Flight Leg</description>
    <fields>
        <fullName>Case__c</fullName>
        <inlineHelpText>The Case to which this Case Complaint is related.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Complaint Codes</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Complaint_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Complaint Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only active Complaint Codes can be selected.</errorMessage>
            <filterItems>
                <field>Complaint_Code__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Only active Complaint Codes can be selected.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Complaint_Code__c</referenceTo>
        <relationshipLabel>Case Complaints</relationshipLabel>
        <relationshipName>Case_Complaints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOT_Disability_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOT Disability Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Complaint_Code__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Dot_Disability</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Complaint_Code__c</referenceTo>
        <relationshipLabel>Case Complaints (DOT Disability Code)</relationshipLabel>
        <relationshipName>DOT_Disability_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Complaint</label>
    <nameField>
        <displayFormat>CPT-{00000000}</displayFormat>
        <label>Case Complaint</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Complaints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Complaint_Code__c.object
<CustomObject>
    <fields>
        <fullName>Disability_Code_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Disability Code Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Complaint Code</label>
    <nameField>
        <label>Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Codes</pluralLabel>
    <recordTypes>
        <fullName>DOT</fullName>
        <active>true</active>
        <label>DOT</label>
    </recordTypes>
    <recordTypes>
        <fullName>Delta</fullName>
        <active>true</active>
        <label>Delta</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dot_Disability</fullName>
        <active>true</active>
        <label>Dot Disability</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/CaseHandler.cls
/*******************************************************//**

@class      CaseHandler

@brief      Trigger Handler for Cases

    This class is called by the Case trigger to manage Cases.

@author     Glyn Anderson   (LiquidHub.GHA)

@version    2015-12-01  LiquidHub.GHA
    Created.

@see        CaseTrigger (trigger)
@see        CaseHandlerTest

    (c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

    This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

public without sharing class CaseHandler implements CWTrigger.Handler
{
    public static set<id> caseId{get;set;}
    /*******************************************************
                        beforeTrigger
    *******************************************************/

    public void beforeTrigger( CWTrigger theTrigger )
    {
        theTrigger.flag     = true;         //  prevent re-triggering on these records

        //  nothing to do here yet...
    }

    /*******************************************************
                        afterTrigger
    *******************************************************/

    public void afterTrigger( CWTrigger theTrigger )
    {
        theTrigger.flag     = true;         //  prevent re-triggering on these records

        //  nothing to do here yet...
    }
    
    public static void beforeCaseUpdate(list<case> caseList, map<id,case> oldmap,map<id,case> newmap)
    {
        map<id,map<string,integer>> caseMap = new map<id,map<string,integer>>();
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        caseId = new set<id>();
        for(case cs:caseList)
        {
            if((oldmap.get(cs.id).Status != newmap.get(cs.id).Status)&&(cs.Status == 'Closed'))
            {
                caseId.add(cs.id);
            }
            
            //Added my Amol-PHX-122
          
             Boolean oldOppIsClosed = oldmap.get(cs.id).Status.equals('Closed');
             Boolean newOppIsClosed = cs.Status.equals('Closed');
             // Check that the field was changed to the status correct value
             if (oldOppIsClosed==true && newOppIsClosed==true) {
                   newmap.get(cs.id).addError('Case Cannot be edited in Closed status.Please Re-open & Edit it');
               }
            //end code  PHX-122
        }
        if(caseId.size() > 0)
        {
            list<case> DOTCases = [select id, Type,SSR__c ,Disability_Code_Required__c ,RecordType.developerName,(select id,Complaint_Code__r.Recordtype.developerName,DOT_Disability_Code__r.Recordtype.developerName,DOT_Disability_Code__c from Case_Complaints__r) from case where id IN :caseId ];
            for(case c: DOTCases)
            {
                integer recordTypeCount = 0;
                map<string,integer> complaintTypeMap = new map<string,integer>();
                for(Case_Complaint__c cc: c.Case_Complaints__r)
                {
                    if(complaintTypeMap.keyset().contains(cc.Complaint_Code__r.Recordtype.developerName))
                    {
                        if(cc.DOT_Disability_Code__c == null){
                        complaintTypeMap.put(cc.Complaint_Code__r.Recordtype.developerName,complaintTypeMap.get(cc.Complaint_Code__r.Recordtype.developerName)+1);
                        }
                        else{
                        if(complaintTypeMap.keyset().contains(cc.DOT_Disability_Code__r.Recordtype.developerName)){
                           complaintTypeMap.put(cc.DOT_Disability_Code__r.Recordtype.developerName,complaintTypeMap.get(cc.DOT_Disability_Code__r.Recordtype.developerName)+1);
                        }
                        else{
                        complaintTypeMap.put(cc.DOT_Disability_Code__r.Recordtype.developerName,1);
                        }
                        }
                        
                    }
                    else{
                        //if(cc.DOT_Disability_Code__c == null){
                        complaintTypeMap.put(cc.Complaint_Code__r.Recordtype.developerName,1);
                        //}
                        if(cc.DOT_Disability_Code__c != null){
                        complaintTypeMap.put(cc.DOT_Disability_Code__r.Recordtype.developerName,1);
                        }
                    }
                    
                }
                caseMap.put(c.id,complaintTypeMap);
                if(c.RecordType.developerName == 'DOT')
                {
                    if((profileName == 'DOT Coordinator')&&(c.Type != 'Disability'))
                    {
                        if((!complaintTypeMap.keyset().contains('DOT'))||(!complaintTypeMap.keyset().contains('Delta')))
                            newmap.get(c.id).addError('Case should have DOT and Delta complaint codes');
                    }
                    if((profileName == 'DOT Coordinator')&&(c.Type == 'Disability'))
                    {
                        if((!complaintTypeMap.keyset().contains('DOT'))||(!complaintTypeMap.keyset().contains('Delta'))||(!complaintTypeMap.keyset().contains('Dot_Disability')))
                            newmap.get(c.id).addError('Case should have DOT code, 1 Delta disability code and the respective DOT disability code.');
                    }
                    
                                        
                }
                if(c.RecordType.developerName == 'Disability')
                {
                   
                  if((c.Type == 'Disability')&&(profileName == 'Disability Coordinator')&&(c.SSR__c == ''))newmap.get(c.id).addError('Please select SSR');
                  if((profileName == 'Disability Coordinator')&&(c.Type == 'Disability'))
                    {
                        if((!complaintTypeMap.keyset().contains('Delta'))||(!complaintTypeMap.keyset().contains('Dot_Disability')))
                            newmap.get(c.id).addError('Case should have 1 Delta disability code and the respective DOT disability code.');
                    }
                }
            }
            
           
        }
    }
}