Efmub-Ogy/src/objects/CWTestObject__c.object
<CustomObject>
    <description>This object is used by CW Framework test classes.  Outside of tests, no records of this object should exist.</description>
    <fields>
        <fullName>Text_40__c</fullName>
        <label>Text 40</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>CWTestObject</label>
    <nameField>
        <displayFormat>CWTest-{000000}</displayFormat>
        <label>CWTestObject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CWTestObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/libKeyFunctionTest.cls
/*******************************************************//**

@class		CWKeyFunctionTest

@brief		Tests for CWKeyFunction Class

	The CWKeyFunctionTest class contains the test methods for the
	CWKeyFunction class.

@author		Glyn Anderson	(LiquidHub.GHA)

@version	2014-12-17	LiquidHub.GHA
	Created.

@see		CWKeyFunction

	(c)2014-2015 LiquidHub.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of CW Core (tm), LiquidHub's middleware library for Salesforce.

***********************************************************/

@isTest
private class CWKeyFunctionTest
{
	private class KeyFunctionTest extends CWKeyFunction
	{
		public override Object getKey( sObject theRecord )
		{
			return	theRecord.get( 'Text_40__c' );
		}
	}

	static testMethod void testKeyFunction()
	{
		List<CWTestObject__c>	testObjects		= new List<CWTestObject__c>
		{
			new CWTestObject__c( Text_40__c = 'A' ),
			new CWTestObject__c( Text_40__c = 'B' ),
			new CWTestObject__c( Text_40__c = 'C' ),
			new CWTestObject__c( Text_40__c = 'D' )
		};

		(new CWIterable( (Iterable<Object>) testObjects, (CWFunction) new KeyFunctionTest() )).toList();
	}
}