Efmub-Ogy/src/objects/Delay_Code__c.object
<CustomObject>
    <description>Represents a Delay Code associated with a Flight Leg.</description>
    <fields>
        <fullName>Flight_Leg__c</fullName>
        <inlineHelpText>The Flight Leg to which this Delay Code is related.</inlineHelpText>
        <label>Flight Leg</label>
        <referenceTo>Flight_Leg__c</referenceTo>
        <relationshipLabel>Delay Codes</relationshipLabel>
        <relationshipName>Delay_Codes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delay Code</label>
    <nameField>
        <displayFormat>DC{00000000}</displayFormat>
        <label>Delay Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delay Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Efmub-Ogy/src/objects/Flight_Leg__c.object
<CustomObject>
    <description>Represents a specific flight leg.</description>
    <label>Flight Leg</label>
    <nameField>
        <label>Flight Leg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flight Legs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Efmub-Ogy/src/classes/DelayCodeHandlerTest.cls
/*******************************************************//**

@class		DelayCodeHandlerTest

@brief		Test Class for the DelayCodeHandler Class

@author		Glyn Anderson (LiquidHub.GHA)

@version	2015-12-01	LiquidHub.GHA
	Created.

@see		DelayCodeHandler
@see		DelayCode (trigger)

	(c)2015 Delta Air Lines, Inc.  All Rights Reserved.  Unauthorized use is prohibited.

	This is a component of @SolutionName, Delta's Case Management App for Salesforce.

***********************************************************/

@isTest
public class DelayCodeHandlerTest
{
	public static testMethod void testDelayCodeHandler()
	{
		CWTest testResults = new CWTest( 'testDelayCodeHandler' );

		Flight_Leg__c	flightLeg	= new Flight_Leg__c();
		insert flightLeg;

		Delay_Code__c	delayCode	= new Delay_Code__c
		(	Flight_Leg__c	= flightLeg.Id
		);

		testResults.startTest();

		insert delayCode;

		//	test code goes here...

		testResults.stopTest();
		testResults.report();
	}
}